server:
  port: 9394    #服务端口
  servlet:
    context-path: /cat  #应用请求上下文路径

spring:
  application:
    name: feign-client-cat  #spring 应用名称，默认也是微服务名称

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9393/eureka/ #eureka 服务器请求路径
  instance:
    prefer-ip-address: true # IP 使用实际 ip 注册
    instance-id: feign-cat # eureka 节点名称

feign:
  hystrix:
    enabled: true  # 开启 feign 的 hystrix 断路器功能。默认为 false，不开启
  name:
    food: eureka-client-food  #自定义参数，用于 @FeignClient 动态取值

#配置 actuator
management:
  endpoint:
    health:
      show-details: always #将健康信息的细节展示给所有用户查看，默认为 never(不展示细节给所有用户)