server:
  port: 9394    #\u670D\u52A1\u5668\u7AEF\u53E3
  servlet:
    context-path: /cat  #\u5E94\u7528\u8BBF\u95EE\u4E0A\u4E0B\u6587

spring:
  application:
    name: feign-client-cat  #\u5FAE\u670D\u52A1\u540D\u79F0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9393/eureka/ #eureka \u670D\u52A1\u5668\u5730\u5740
  instance:
    prefer-ip-address: true # IP \u5730\u5740\u4EE3\u66FF\u4E3B\u673A\u540D\u6CE8\u518C
    instance-id: feign-cat # \u5FAE\u670D\u52A1\u5B9E\u4F8Bid\u540D\u79F0
